### ISSUE TITLE
起動中に電源を切るとbundlerでエラーになってしまう

### ISSUE THREAD

**Issue by jiikko** [splaplapla/procon_bypass_man#117]
gitで管理している内部のファイルが不正状態になっていてgitコマンドが失敗してしまっている。リカバリーしたい。

```
pi@ras1:/usr/share/pbm/current $ /home/pi/.rbenv/versions/3.0.1/bin/ruby app.rb
/home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/source/git/git_proxy.rb:175:in `git': Git error: command `git fetch --force --quiet --tags https://github.com/splaplapla/procon_bypass_man refs/heads/\\*:refs/heads/\\*` in directory /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/cache/bundler/git/procon_bypass_man-ae4c9016d76b667658c8ba66f3bbd2eebf2656af has failed. (Bundler::Source::Git::GitCommandError)

If this error persists you could try removing the cache directory '/home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/cache/bundler/git/procon_bypass_man-ae4c9016d76b667658c8ba66f3bbd2eebf2656af'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/source/git/git_proxy.rb:162:in `block in git_retry'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/retry.rb:40:in `run'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/retry.rb:30:in `attempt'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/source/git/git_proxy.rb:161:in `git_retry'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/source/git/git_proxy.rb:106:in `block in checkout'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/source/git/git_proxy.rb:218:in `with_path'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/source/git/git_proxy.rb:105:in `checkout'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/source/git.rb:310:in `fetch'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/source/git.rb:164:in `specs'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/definition.rb:783:in `block in converge_locked_specs'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/definition.rb:769:in `each'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/definition.rb:769:in `converge_locked_specs'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/definition.rb:271:in `resolve'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/definition.rb:185:in `specs'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/definition.rb:173:in `resolve_remotely!'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/installer.rb:291:in `resolve_if_needed'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/installer.rb:83:in `block in run'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/process_lock.rb:12:in `block in lock'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/process_lock.rb:9:in `open'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/process_lock.rb:9:in `lock'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/installer.rb:72:in `run'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/installer.rb:24:in `install'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/inline.rb:63:in `block (2 levels) in gemfile'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/settings.rb:115:in `temporary'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/inline.rb:62:in `block in gemfile'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/settings.rb:115:in `temporary'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/inline.rb:55:in `gemfile'
        from app.rb:5:in `<main>'
```

エラーメッセージからcache directoryを取得して削除するか。

**Comment by jiikko** [comment]
https://github.com/splaplapla/procon_bypass_man/commit/606ec42dd49a3fa28223250c2170423fc913a3b2 で対応した
