### ISSUE TITLE
接続中にプロコンのケーブルを物理的抜くとエラーメッセージが無限に出力する

### ISSUE THREAD

**Issue by jiikko** [splaplapla/procon_bypass_man#124]
```
D, [2022-05-13T23:08:42.388669 #1029] DEBUG -- : direct_connect_switch_via_bluetooth!
E, [2022-05-13T23:08:42.389380 #1029] ERROR -- : Proconが切断されました。終了処理を開始します2. <internal:io>:121:in `write_nonblock': No such device @ io_write_nonblock - /dev/hidraw0 (Errno::ENODEV)
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass.rb:101:in `direct_connect_switch_via_bluetooth'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass/bypass_command.rb:72:in `block (2 levels) in execute'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass/bypass_command.rb:69:in `loop'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass/bypass_command.rb:69:in `block in execute'

D, [2022-05-13T23:08:43.132746 #1029] DEBUG -- : direct_connect_switch_via_bluetooth!
E, [2022-05-13T23:08:43.133727 #1029] ERROR -- : Proconが切断されました。終了処理を開始します2. <internal:io>:121:in `write_nonblock': No such device @ io_write_nonblock - /dev/hidraw0 (Errno::ENODEV)
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass.rb:101:in `direct_connect_switch_via_bluetooth'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass/bypass_command.rb:72:in `block (2 levels) in execute'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass/bypass_command.rb:69:in `loop'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass/bypass_command.rb:69:in `block in execute'

D, [2022-05-13T23:08:43.877367 #1029] DEBUG -- : direct_connect_switch_via_bluetooth!
E, [2022-05-13T23:08:43.878191 #1029] ERROR -- : Proconが切断されました。終了処理を開始します2. <internal:io>:121:in `write_nonblock': No such device @ io_write_nonblock - /dev/hidraw0 (Errno::ENODEV)
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass.rb:101:in `direct_connect_switch_via_bluetooth'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass/bypass_command.rb:72:in `block (2 levels) in execute'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass/bypass_command.rb:69:in `loop'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass/bypass_command.rb:69:in `block in execute'

D, [2022-05-13T23:08:44.626490 #1029] DEBUG -- : direct_connect_switch_via_bluetooth!
E, [2022-05-13T23:08:44.627140 #1029] ERROR -- : Proconが切断されました。終了処理を開始します2. <internal:io>:121:in `write_nonblock': No such device @ io_write_nonblock - /dev/hidraw0 (Errno::ENODEV)
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass.rb:101:in `direct_connect_switch_via_bluetooth'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass/bypass_command.rb:72:in `block (2 levels) in execute'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass/bypass_command.rb:69:in `loop'
        from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-6edf4cab64df/lib/procon_bypass_man/bypass/bypass_command.rb:69:in `block in execute'
```

**Comment by jiikko** [comment]
https://github.com/splaplapla/procon_bypass_man/pull/123/commits/48a5fc12b66c6661c81defbb9032b378ee442b9c で修正した
