### ISSUE TITLE
設定ファイルの再読み込みに失敗したらプロセスがハングしてしまう

### ISSUE THREAD

**Issue by jiikko** [splaplapla/procon_bypass_man#34]
`[2022-02-05T12:49:48.825968 #1178] ERROR -- : 設定ファイルが不正です。再読み込みができませんでした`

読み込みができなかったらreloadしないで接続を維持したい

```
Feb 06 18:08:25 raspberrypi2 bash[582]: Reloading config file
Feb 06 18:08:25 raspberrypi2 bash[582]: 設定ファイルが不正です。再読み込みができませんでした
Feb 06 18:08:26 raspberrypi2 bash[582]: バイパス処理を再開します
Feb 06 18:08:26 raspberrypi2 bash[582]: #<Thread:0x02f25108 /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/commands/bypass_command.rb:57 run> terminated with exception (report_on_exception is true):
Feb 06 18:08:26 raspberrypi2 bash[582]: /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/procon/layer_changer.rb:27:in `change_layer?': prefix_keysが未設定です (RuntimeError)
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/procon.rb:43:in `apply!'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/processor.rb:13:in `process'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/bypass.rb:82:in `block in send_procon_to_gadget!'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/support/callbacks.rb:50:in `run_callbacks'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/bypass.rb:55:in `send_procon_to_gadget!'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/commands/bypass_command.rb:61:in `block (2 levels) in execute'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/commands/bypass_command.rb:59:in `loop'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/commands/bypass_command.rb:59:in `block in execute'
Feb 06 18:08:26 raspberrypi2 bash[582]: /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/procon/layer_changer.rb:27:in `change_layer?': prefix_keysが未設定です (RuntimeError)
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/procon.rb:43:in `apply!'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/processor.rb:13:in `process'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/bypass.rb:82:in `block in send_procon_to_gadget!'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/support/callbacks.rb:50:in `run_callbacks'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/bypass.rb:55:in `send_procon_to_gadget!'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/commands/bypass_command.rb:61:in `block (2 levels) in execute'
Feb 06 18:08:26 raspberrypi2 bash[582]:         from /home/pi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/procon_bypass_man-27a088e74960/lib/procon_bypass_man/commands/bypass_command.rb:59:in `loop'
Feb 06 18:08:26 raspberrypi2 bash[58
```

**Comment by jiikko** [comment]
v0.1.19でリリースする
